export const SEO_KEYWORDS = [
  "Titan Arena Gaming",
  "Free Fire",
  "Free Fire Max",
  "Free Fire Custom Rooms",
  "Free Fire Tournaments",
  "Free Fire India",
  "Custom Free Fire Room Matches",
  "Titan Arena Room Match",
  "Titan Arena Youtube Channel",
  "Free Fire Gaming Platform",
  "Cash Prize Tournaments",
  "Free Fire Solo Matches",
  "Free Fire Duo Matches",
  "Free Fire Squad Matches",
  "Leaderboard",
  "Bet Match",
  "Online Free Fire Gaming",
  "Esports India",
  "Free Fire Tournament",
];
