export const SEO_KEYWORDS = [
  "Titan Arena Gaming",
  "Free Fire",
  "Free Fire Max",
  "Free Fire Custom Rooms",
  "Free Fire Tournaments",
  "Free Fire India",
  "Custom Room Matches",
  "Esports",
  "Gaming Platform",
  "Cash Prize Tournaments",
  "Solo Matches",
  "Duo Matches",
  "Squad Matches",
  "Leaderboard",
  "Prize Pool",
  "Online Gaming",
  "Esports India",
  "Tournament Platform",
];
